# Generated by Django 5.2.4 on 2026-09-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_appointmentservice_price_at_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
    ]
